sudo: required
services:
  - docker

before_install:
  - docker build -t tandrtc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tandrtc/react-test npm test -- --coverage

after_success:
  - docker build -t tandrtc/multi-client ./client
  - docker build -t tandrtc/multi-nginx ./nginx
  - docker build -t tandrtc/multi-server ./server
  - docker build -t tandrtc/multi-worker ./worker
  # log into Docker CLI
  - echo "$DOCKERPASS" | docker login -u "$DOCKERID" --password--stdin
  # Push built images
  - docker push tandrtc/multi-client
  - docker push tandrtc/multi-nginx
  - docker push tandrtc/multi-server
  - docker push tandrtc/multi-worker
